# Generated by Django 3.1.14 on 2023-08-20 11:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название покемона')),
                ('photo', models.ImageField(blank=True, upload_to='pokemons_photo', verbose_name='Фото покемона')),
                ('eng_name', models.CharField(blank=True, max_length=30, verbose_name='Перевод на английский')),
                ('jap_name', models.CharField(blank=True, max_length=30, verbose_name='Перевод на японский')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Описание')),
                ('evolution_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_evolution', to='pokemon_entities.pokemon', verbose_name='Эволюционировал из')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('appeared_at', models.DateTimeField(verbose_name='Дата появления')),
                ('disappeared_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата исчезновения')),
                ('level', models.IntegerField(blank=True, default=1, null=True, verbose_name='Уровень')),
                ('health', models.IntegerField(blank=True, default=100, null=True, verbose_name='Здоровье')),
                ('strength', models.IntegerField(blank=True, default=100, null=True, verbose_name='Сила')),
                ('defence', models.IntegerField(blank=True, default=100, null=True, verbose_name='Защита')),
                ('stamina', models.IntegerField(blank=True, default=100, null=True, verbose_name='Выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_entity', to='pokemon_entities.pokemon', verbose_name='Название покемона')),
            ],
        ),
    ]
