# Generated by Django 3.1.14 on 2023-08-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_auto_20230816_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='photo',
            field=models.ImageField(blank=True, upload_to='pokemons_photo/'),
        ),
    ]
